version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://blog_user:blog_password@db:5432/blog_db?schema=public
      ADMIN_SECRET: change-this-admin-secret
      NEXT_PUBLIC_SITE_URL: http://localhost:3000

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
